package com.example.entity;
// default package

// Generated Oct 12, 2015 5:02:49 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserPhoto generated by hbm2java
 */
@Entity
@Table(name = "user_photo", schema = "public")
public class UserPhoto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8462755694904927323L;
	private int photoId;
	private String photoName;
	private byte[] photoData;
	private Set<Users> userses = new HashSet<Users>(0);

	public UserPhoto() {
	}

	public UserPhoto(int photoId) {
		this.photoId = photoId;
	}

	public UserPhoto(int photoId, String photoName, byte[] photoData, Set<Users> userses) {
		this.photoId = photoId;
		this.photoName = photoName;
		this.photoData = photoData;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "photo_id", unique = true, nullable = false)
	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(int photoId) {
		this.photoId = photoId;
	}

	@Column(name = "photo_name")
	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	@Column(name = "photo_data")
	public byte[] getPhotoData() {
		return this.photoData;
	}

	public void setPhotoData(byte[] photoData) {
		this.photoData = photoData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userPhoto")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
